### ISSUE TITLE
How to use natbib with this template?

### ISSUE THREAD

**Issue by KonradHoeffner** [vtex-soft/texsupport.iospress-sw#1]
Is it allowed to use natbib for \citet and \citep? It seems like those commands are already defined but \citet causes an "(author?)" to appear in the text even though the authors are defined in the bibtex file.

**Comment by mingiss** [comment]
Sorry for late answer.

Commands \citet and \citep are intended for use with author-year citation style, like in the "Applied Ontology" journal:
https://github.com/vtex-soft/texsupport.iospress-ao
"Semantic Web" journal is designed to use the number reference citation style, therefore, mentioned commands should not be used.

Regards, Mindaugas.

**Comment by KonradHoeffner** [comment]
Thanks, that answers my question!
